#!/bin/bash

if [ !  -d ~/Projects/ ]; then
   #Create root ~/Projects dir
   echo "Projects root dir not found, Creating..." 
   mkdir ~/Projects
fi
cd ~/Projects/

#Creating new investigation structure
echo "Create folder for investation: $1"
mkdir $1
cd $1
mkdir EPT IPT

cp ~/Scripts/startEnum EPT
#cd EPT && mkdir evidence logs scans scope tools
#cd evidence && mkdir credentials data screenshots

cd ../..
cp /home/marquez/Scripts/startEnum IPT
#cd IPT && mkdir evidence logs scans scope tools
#cd evidence && mkdir credentials data screenshots
echo "Project succesfully created"

