#!/bin/bash

if [ !  -d ~/projects/ ]; then
   #Create root ~/Projects dir
   echo "Projects root dir not found, Creating..." 
   mkdir ~/projects
fi
cd ~/projects/

#Creating new investigation structure
echo "Create folder for investation: $1"
mkdir $1
cd $1
mkdir EPT IPT

cp ~/scripts/* EPT
#cd EPT && mkdir evidence logs scans scope tools
#cd evidence && mkdir credentials data screenshots

cd ../..
cp ~/scripts/* IPT
#cd IPT && mkdir evidence logs scans scope tools
#cd evidence && mkdir credentials data screenshots
echo "Project succesfully created"

