#!/bin/bash

TARGET_DOMAIN=$1

#Creates tmux session and splits by 3
tmux new -d -s reconnaince -n recon
tmux split-window -h -t recon
tmux split-window -v -t recon

#######################################################################
### Install tools #####################################################
#######################################################################
tmux send-keys -t recon.0 "/bin/bash ~/tools/amass_setup.sh" C-m
tmux send-keys -t recon.1 "/bin/bash ~/tools/recon-ng_setup.sh" C-m
#tmux send-keys -t recon.2 "~/tools/harverst.sh $TARGET_DOMAIN" C-m

#######################################################################
### Executing commands ################################################
#######################################################################
tmux list-panes -F '#{session_name}:#{window_index}.#{pane_index}' -f reconnaince | xargs -I PANE tmux send-keys -t PANE 'source ~/.profile' C-m



#######################################################################
### Amass commands ####################################################
#######################################################################
tmux send-keys -t recon.0 "amass enum -d $TARGET_DOMAIN" C-m
